##########################################
########## Amlogic Drivers ###############
##########################################
obj-$(CONFIG_AMLOGIC_MEDIA_CANVAS)    += canvas/
obj-$(CONFIG_SND_SOC)                 += codecs/
obj-$(CONFIG_AMLOGIC_REBOOT)          += reboot/
obj-$(CONFIG_AMLOGIC_SEC)             += secmon/
obj-$(CONFIG_AMLOGIC_EFUSE_UNIFYKEY)  += unifykey/
obj-$(CONFIG_MMC_MESON_GX)            += mmc/
obj-$(CONFIG_AMLOGIC_IOMAP)           += iomap/
obj-$(CONFIG_AMLOGIC_CPU_VERSION)     += cpu_version/
obj-$(CONFIG_AMLOGIC_MEDIA)           += media/
obj-$(CONFIG_AMLOGIC_MEDIA_GE2D)      += ge2d/
obj-$(CONFIG_AMLOGIC_INPUT)           += input/
obj-$(CONFIG_AMLOGIC_UART)            += uart/
obj-$(CONFIG_PHY_MESON_G12A_MIPI_DPHY_ANALOG) += phy/
obj-$(CONFIG_MESON_GX_PM)             += pm/