# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel drivers.
#
#

# vendor drivers
VENDOR_DRIVERS_PREFIX := ../../../../..
obj-y		+= $(VENDOR_DRIVERS_PREFIX)/device/board/$(PRODUCT_COMPANY)/$(DEVICE_NAME)/kernel/drivers/

obj-$(CONFIG_ARCH_MESON)	+= amlogic/
